create database if not exists shopping_cart_pure_php character set UTF8 collate utf8_unicode_ci;
use shopping_cart_pure_php;

create table product
(
    id       int          not null primary key auto_increment,
    _name    varchar(100) not null,
    quantity varchar(500),
    color    varchar(50),
    size     varchar(10),
    price    int          not null,
    img      longtext     not null,
    detail   longtext     not null
);

INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('1', 'Macbook Pro', '1', 'Gray', '20', '9000000', 'macbook.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('2', 'iPhone 12 Pro Max', '1', 'Black', '12', '6000000', 'iphone12.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('3', 'iPad Pro 11', '1', 'White', '8', '3600000', 'ipad-pro.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('4', 'Apple Watch', '1', 'Black', '10', '1200000', 'apple-watch.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('5', 'Ear Bud', '1', 'Gold', '3', '5300000', 'earbud.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('6', 'Razer Ultimate', '1', 'Pink', '5', '1200000', 'keyboard-razer.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('7', 'SteelSeries Keyboard', '1', 'Black', '16', '5000000', 'steelseries-keyboard.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');
INSERT INTO `shopping_cart_pure_php`.`product` (`id`, `_name`, `quantity`, `color`, `size`, `price`, `img`, `detail`) VALUES ('8', 'Rival Mouse', '1', 'Gray', '14', '7500000', 'rival-mouse.jpg', 'CPU: Apple M1/RAM: 8GB/Hardware: SSD 512GB/Screen: 13.3inch Retina/OS: MacOS/Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged');

